package com.fnklabs.td.gui;

import com.intellij.uiDesigner.core.Spacer;
import org.usb4java.Device;

import javax.swing.*;
import javax.swing.plaf.DimensionUIResource;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class GuiApplication extends JFrame {
    private JButton okBtn;
    private JPanel rootPanel;
    private JButton devices;
    private JPanel top;
    private JPanel menu;
    private JPanel middle;
    private JPanel footer;
    private JLabel antStatus;
    private JLabel antStatusValue;

    public GuiApplication() throws HeadlessException {
        setContentPane(rootPanel);
        setVisible(true);
        setMinimumSize(new DimensionUIResource(400, 300));
        setMaximumSize(new DimensionUIResource(400, Integer.MAX_VALUE));

        getContentPane().setPreferredSize(new DimensionUIResource(300, 300));
        setLocationRelativeTo(null);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        devices.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                Device antDevice = null;//UsbDevices.INSTANCE.findAntDevice();

                if (antDevice != null) {
                    antStatusValue.setText(String.format("Connected: %s", antDevice));
                }
            }
        });
    }

    public static void main(String[] args) {
        new GuiApplication();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        top = new JPanel();
        top.setLayout(new BorderLayout(0, 0));
        rootPanel.add(top, BorderLayout.NORTH);
        menu = new JPanel();
        menu.setLayout(new BorderLayout(0, 0));
        menu.setEnabled(false);
        top.add(menu, BorderLayout.EAST);
        devices = new JButton();
        devices.setText("Refresh devices");
        menu.add(devices, BorderLayout.WEST);
        okBtn = new JButton();
        okBtn.setText("Workouts");
        menu.add(okBtn, BorderLayout.CENTER);
        final Spacer spacer1 = new Spacer();
        top.add(spacer1, BorderLayout.CENTER);
        middle = new JPanel();
        middle.setLayout(new BorderLayout(0, 0));
        rootPanel.add(middle, BorderLayout.CENTER);
        footer = new JPanel();
        footer.setLayout(new BorderLayout(0, 0));
        middle.add(footer, BorderLayout.SOUTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        footer.add(panel1, BorderLayout.WEST);
        antStatus = new JLabel();
        antStatus.setText("Ant+ Status:");
        panel1.add(antStatus, BorderLayout.CENTER);
        antStatusValue = new JLabel();
        antStatusValue.setText("Not connected");
        panel1.add(antStatusValue, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
